namespace WpfApplication1.Enums
{
    public enum StepType
    {
        LaunchIe,
        AttachIe,
        Navigate,
        HttpGetData,
        WaitForElement,
        WaitPageReady,
        ClickElement,
        ClickAndSwitchWindow,
        InputText,
        ReadText,
        SelectOption,
        SwitchFrame,
        PageListLoop,
        QueryAndExportReport,
        HttpUploadFile,
        UpdateBusinessState,
        SwitchWindow,
        ExecuteScript,
        HandleAlert,
        UploadFile,
        WaitDownload,
        SetVariable,
        Condition,
        Loop,
        LoopStart,
        LoopEnd,
        Delay,
        Screenshot,
        WriteLog
    }
}